import type { Business, Category, MenuItem } from "./types";

export const demoBusiness: Business = {
  name: "Savor & Co.",
  heroEyebrow: "Welcome to the table",
  heroTitle: "Good food.",
  heroEmphasis: "Beautifully simple.",
  description: "Season-led comfort food, crafted with soul.",
  logo: "SC",
  coverImage:
    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1800&q=85",
  address: "12 Zamalek Avenue, Cairo",
  phone: "+20 100 555 0142",
  whatsapp: "201005550142",
  instagram: "https://instagram.com",
  facebook: "https://facebook.com",
  openingHours: "Open daily · 8:00 AM — 11:30 PM",
  currency: "EGP",
  hideUnavailable: false,
};
export const demoCategories: Category[] = [
  {
    _id: "c1",
    name: "Breakfast",
    slug: "breakfast",
    description: "A bright start",
    order: 1,
    active: true,
  },
  {
    _id: "c2",
    name: "Burgers",
    slug: "burgers",
    description: "Hand-smashed favorites",
    order: 2,
    active: true,
  },
  {
    _id: "c3",
    name: "Main Courses",
    slug: "mains",
    description: "From our kitchen",
    order: 3,
    active: true,
  },
  {
    _id: "c4",
    name: "Desserts",
    slug: "desserts",
    description: "Save room",
    order: 4,
    active: true,
  },
  {
    _id: "c5",
    name: "Drinks",
    slug: "drinks",
    description: "Hot and cold",
    order: 5,
    active: true,
  },
];
const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;
export const demoItems: MenuItem[] = [
  {
    _id: "p1",
    name: "Turkish Eggs",
    slug: "turkish-eggs",
    description:
      "Garlic labneh, soft eggs, Aleppo butter, dill and toasted sourdough.",
    price: 165,
    image: img("photo-1525351484163-7529414344d8"),
    category: demoCategories[0],
    available: true,
    featured: true,
    isNew: false,
    bestSeller: true,
    sizes: [],
    extras: [
      { name: "Extra sourdough", price: 20 },
      { name: "Avocado", price: 45 },
    ],
    order: 1,
  },
  {
    _id: "p2",
    name: "Honey Ricotta Toast",
    slug: "honey-ricotta",
    description:
      "Whipped ricotta, local honey, roasted figs, pistachio and sea salt.",
    price: 145,
    image: img("photo-1484723091739-30a097e8f929"),
    category: demoCategories[0],
    available: true,
    featured: false,
    isNew: true,
    bestSeller: false,
    sizes: [],
    extras: [],
    order: 2,
  },
  {
    _id: "p3",
    name: "The Savor Burger",
    slug: "savor-burger",
    description:
      "Double smashed beef, aged cheddar, caramelized onions, pickles and house sauce.",
    price: 250,
    discountPrice: 199,
    image: img("photo-1568901346375-23c9450c58cd"),
    category: demoCategories[1],
    available: true,
    featured: true,
    isNew: false,
    bestSeller: true,
    sizes: [],
    extras: [
      { name: "Extra cheese", price: 20 },
      { name: "Beef patty", price: 70 },
      { name: "Truffle sauce", price: 25 },
    ],
    order: 1,
  },
  {
    _id: "p4",
    name: "Hot Honey Chicken",
    slug: "hot-honey-chicken",
    description:
      "Crispy chicken, cabbage slaw, pickles and spiced honey on brioche.",
    price: 210,
    image: img("photo-1615297928064-24977384d0da"),
    category: demoCategories[1],
    available: false,
    featured: false,
    isNew: true,
    bestSeller: false,
    sizes: [],
    extras: [],
    order: 2,
  },
  {
    _id: "p5",
    name: "Miso Glazed Salmon",
    slug: "miso-salmon",
    description:
      "Roasted salmon, sesame greens, jasmine rice and ginger scallion dressing.",
    price: 390,
    image: img("photo-1467003909585-2f8a72700288"),
    category: demoCategories[2],
    available: true,
    featured: true,
    isNew: false,
    bestSeller: false,
    sizes: [],
    extras: [],
    order: 1,
  },
  {
    _id: "p6",
    name: "Truffle Mushroom Pasta",
    slug: "truffle-pasta",
    description:
      "Fresh tagliatelle, wild mushrooms, parmesan, herbs and truffle cream.",
    price: 285,
    image: img("photo-1473093295043-cdd812d0e601"),
    category: demoCategories[2],
    available: true,
    featured: false,
    isNew: false,
    bestSeller: true,
    sizes: [
      { name: "Regular", price: 285 },
      { name: "Large", price: 340 },
    ],
    extras: [{ name: "Grilled chicken", price: 65 }],
    order: 2,
  },
  {
    _id: "p7",
    name: "Burnt Basque Cheesecake",
    slug: "basque-cheesecake",
    description: "Caramelized top, silky center and seasonal berry compote.",
    price: 135,
    image: img("photo-1578985545062-69928b1d9587"),
    category: demoCategories[3],
    available: true,
    featured: false,
    isNew: false,
    bestSeller: true,
    sizes: [],
    extras: [],
    order: 1,
  },
  {
    _id: "p8",
    name: "Spanish Latte",
    slug: "spanish-latte",
    description:
      "Double espresso, textured milk and our signature condensed milk blend.",
    price: 95,
    image: img("photo-1509042239860-f550ce710b93"),
    category: demoCategories[4],
    available: true,
    featured: false,
    isNew: false,
    bestSeller: false,
    sizes: [
      { name: "Small", price: 80 },
      { name: "Medium", price: 95 },
      { name: "Large", price: 115 },
    ],
    extras: [
      { name: "Extra shot", price: 20 },
      { name: "Oat milk", price: 25 },
    ],
    order: 1,
  },
];
