export type Option = { name: string; price: number };
export type Category = {
  _id: string;
  name: string;
  nameAr?: string;
  slug: string;
  description?: string;
  image?: string;
  icon?: string;
  order: number;
  active: boolean;
  createdAt?: string;
  updatedAt?: string;
};
export type MenuItem = {
  _id: string;
  name: string;
  nameAr?: string;
  slug: string;
  shortDescription?: string;
  description: string;
  descriptionAr?: string;
  price: number;
  discountPrice?: number;
  image: string;
  images?: string[];
  category: Category | string;
  available: boolean;
  featured: boolean;
  isNew: boolean;
  bestSeller: boolean;
  customBadges?: string[];
  sizes: Option[];
  extras: Option[];
  order: number;
  createdAt?: string;
  updatedAt?: string;
};
export type Appearance = {
  primaryColor: string;
  secondaryColor: string;
  backgroundColor: string;
  textColor: string;
  buttonStyle: "rounded" | "square" | "pill";
  cardStyle: "soft" | "bordered" | "flat";
  theme: "light" | "dark";
};
export type Business = {
  name: string;
  nameAr?: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroEmphasis?: string;
  description: string;
  descriptionAr?: string;
  logo: string;
  coverImage: string;
  address: string;
  mapUrl?: string;
  phone: string;
  whatsapp: string;
  instagram?: string;
  facebook?: string;
  tiktok?: string;
  openingHours: string;
  currency: string;
  deliveryInfo?: string;
  hideUnavailable: boolean;
  defaultLanguage?: "en" | "ar";
  appearance?: Appearance;
};
